### ISSUE TITLE
[SBT] sources under other configurations (like it, for integration tests) not getting picked up.

### ISSUE THREAD

**Issue by rcano** [dcaoyuan/nbscala#131]
When using integration tests, sbt uses a source directory typically under src/it/scala, that directory is not picked up by the ide.

A workaround is to manually add it to the .classpath_nb.

**Comment by akochnev** [comment]
@rcano - can you provide an example project (as simple as possible) where SBT is configured w/ integration tests ?

**Comment by akochnev** [comment]
I was able to reproduce the issue w/o an example project from @rcano ; however, it seems that there is no need for a fix. In order to have the src/it/scala show up in the list of source roots. In my Build.scala, I added : 
// import the netbeans plugin keys
import org.netbeans.nbsbt.core.NetBeansPlugin._

Then, add to the project settings, e.g. : 

lazy val website = Project ("lift-quickstart-website", file("website"),
    settings = BuildSettings.buildSettings ++ Seq (libraryDependencies ++= commonDeps ++ websiteDeps ++ Seq(
      "org.eclipse.jetty" % "jetty-webapp" % "9.0.5.v20130815" % "container",
      //next line needed cause of https://github.com/harrah/xsbt/issues/499
      "org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" % "container" artifacts (Artifact("javax.servlet", "jar", "jar"))
    )) ++ com.earldouglas.xsbtwebplugin.WebPlugin.webSettings ++ Seq(
      scanDirectories in Compile := Nil,
      port in config("container") := 8080
    ) ++ jrebelSettings ++ Seq (
      jrebel.webLinks <++= webappResources in Compile
    ) ++ Seq (
      NetBeansKeys.configurations := Set(Configurations.Compile, Configurations.Test, Configurations.IntegrationTest)
      
    )

With this configuration when nbsbt regenerates the .classpath_nb file, it now includes an entry pointing to the src/it/scala folder, e.g. 
<classpathentry kind="src" path="src/it/scala" output="target/scala-2.10/it-classes" scope="it" managed="false"/>

IMO, this issue can be closed as invalid (maybe some documentation is needed, but this is already supported by nbsbt out of the box).

**Comment by rcano** [comment]
Oh, thanks, I agree. I'm closing it.
